### PR TITLE
Translation Sys

### PR DESCRIPTION
**Pull request by MichelePezza**
I moved to standard translation mode for web extension and added Italian translation.
Fixed an issue in navdropindicator when switchin sidebar/stickyheader.

I added a branch with a new theme could you can kindly give your opinion about it?

### CODE REVIEW

**Comment by mpod** [comment]
Thank you Michele, great stuff. I have two small comments.

**Comment by mpod** [comment]
About Leaf theme. It is interesting, but I'm not sure about it. It needs more work. Borders are too thick, and there are too many of them, for example page border is not needed. Spacing between widgets is not even any more. Also, I don't see an easy way to integrate this new theme with existing themes. I would not merge at this stage.

**Comment by MichelePezza** [comment]
> Thank you Michele, great stuff. I have two small comment

What are the comments?
Can i improve something?

Ciao
MP

**Comment by mpod** [comment]
Yes, your changes break some of the existing things. In 'sticky header' mode config button in right top corner is not properly centered any more. Also, in 'sticky header' mode when you are reordering list of pages, the small indicator bar is not centered properly. Try to play a bit, if you don't find it I can provide you screenshots.

**Comment by MichelePezza** [comment]
> Yes, your changes break some of the existing things. In 'sticky header' mode config button in right top corner is not properly centered any more. Also, in 'sticky header' mode when you are reordering list of pages, the small indicator bar is not centered properly. Try to play a bit, if you don't find it I can provide you screenshots.

I fixed something....
Could you please verify?

Ciao
MP

**Comment by mpod** [comment]
Thank you!

**Pull request merged**
